# Generated by Django 4.2.3 on 2023-07-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_alter_filemetadata_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filemetadata",
            name="size",
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name="filemetadata",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
